#! /bin/bash
## SGE batch file - cpac_FAB
#$ -S /bin/bash
#$ -N cpac_FAB
#$ -pe openmp 8
#$ -l mem_free=2G
#$ -t 1-8 
#$ -V
#$ -wd /mnt/MD1200A/fbarrios/cpac_cluster_files/

module add singularity/2.2

singularity run -B /mnt:/mnt \
  /mnt/MD1200A/fbarrios/fbarrios/singularity_images/cpac_v1.0.0 \
  --n_cpus 8 --mem 16 \
  --data_config_file /mnt/MD1200A/fbarrios/cpac_rsConRDC/cpac_data_config_20161104231240.yml \
  --pipeline_file /mnt/MD1200A/fbarrios/cpac_rsConRDC/pipeline_config_FAB.yml \
  /mnt/MD1200A/fbarrios/cpac_rsConRDC/ \
  /mnt/MD1200A/fbarrios/cpac_rsConRDC/outputs_FAB \
  participant --participant_ndx $(( SGE_TASK_ID - 1 ))
