#! /bin/bash
## SGE batch file - test1
#$ -S /bin/bash
#$ -N benchmark
#$ -pe openmp 7
#$ -t 1-40 
#$ -V
#$ -wd /mnt/MD1200A/fbarrios/fbarrios/cpac_test/outputs_benchmark/cluster_files

module add singularity/2.2

singularity run -B /mnt:/mnt -B /tmp:/tmp \
  /mnt/MD1200A/fbarrios/fbarrios/singularity_images/cpac_v1.0.0 \
  --n_cpus 8 --mem 30 \
  --data_config_file /mnt/MD1200A/fbarrios/rsConRDC/cpac_data_config_20161104231240.yml \
  /mnt/MD1200A/fbarrios/fbarrios/rsConRDC/config_20170228 \
  /mnt/MD1200A/fbarrios/fbarrios/rsConRDC/outputs_config_20170228 \
  participant --participant_ndx $(( SGE_TASK_ID - 1 ))
